"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const authTokenKey = process.env.NEXT_PUBLIC_AUTH_TOKEN
const authTokenValue = localStorage.getItem(authTokenKey);
const getAuth = () => {

  // check if authTokenValue exists and it's not null
  if (authTokenValue && authTokenValue !== null && authTokenValue !== undefined) {
    try {
      const user = JSON.parse(authTokenValue);
      console.log("user", user);
    } catch (error) {
      console.log("error", error);
    }
  }
}
export default function RootLayout({ children }) {
  useEffect(() => {
   localStorage.getItem(authTokenValue);
   console.log("authTokenValue", authTokenValue);
   console.log("authTokenKey", authTokenKey);
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
